// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsL7_rUX29qK-ALQY91hZno-onXPmxljs',
    appId: '1:1004443082016:android:54899fe91f822f7de94b45',
    messagingSenderId: '724928109914',
    projectId: 'english-3367d',
    authDomain: 'flutter-freebies.firebaseapp.com',
    storageBucket: 'flutter-freebies.appspot.com',
    measurementId: 'G-2J3B19Q48B',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyDsL7_rUX29qK-ALQY91hZno-onXPmxljs",
      authDomain: "englishlearn-2562b.firebaseapp.com",
      databaseURL:
          "https://englishlearn-2562b-default-rtdb.europe-west1.firebasedatabase.app",
      projectId: "english-3367d",
      storageBucket: "englishlearn-2562b.appspot.com",
      messagingSenderId: "669664116612",
      appId: "1:1004443082016:android:54899fe91f822f7de94b45",
      measurementId: "G-8Z7JTD9Q5B");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsL7_rUX29qK-ALQY91hZno-onXPmxljs',
    appId: '1:1004443082016:android:54899fe91f822f7de94b45',
    messagingSenderId: '724928109914',
    projectId: 'english-3367d',
    storageBucket: 'flutter-freebies.appspot.com',
    iosClientId:
        '724928109914-1adjc73c1se3jr5shdiuntaujkqgvvre.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsL7_rUX29qK-ALQY91hZno-onXPmxljs',
    appId: '1:1004443082016:android:54899fe91f822f7de94b45',
    messagingSenderId: '724928109914',
    projectId: 'english-3367d',
    storageBucket: 'flutter-freebies.appspot.com',
    iosClientId:
        '724928109914-g3uv4qacao8h2u7an3sdtliqe18c19mc.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen.mac',
  );
}
